#!/bin/sh

# TODO use argument flags

db_name=example
dbs_folder="/tmp/simpleql/dbs"
db_file=$dbs_folder/$db_name.db
csv_folder="/home/wim/code/github/k8-conf-mgmnt/docs/discovery/db/values/"
tables_file="/home/wim/code/github/k8-conf-mgmnt/docs/discovery/db/tables.sql"

mkdir -p $dbs_folder

# create database with tables
cat "$tables_file" | sqlite3 $db_file

# import values from folder of .csv
csv_files=$(find $csv_folder -type f -name '*.csv')
while read line; do 
  table_name=$(basename $line | awk -F '.' '{print $1}');
  sqlite3 $db_file \
    ".mode csv" ".import $line $table_name"
done <<< $csv_files

# delete database
rm $db_file

# list databases
ls -l $dbs_folder

# show all tables with headers and table format

# --help
